### ISSUE TITLE
Cannot find your contact info

### ISSUE THREAD

**Issue by donat** [Lorenzo0111/Lorenzo0111#8]
Hi @Lorenzo0111! I'm Donat Csikos, an engineer at Gradle. I saw a Gradle plugin portal submission from you, and I need to send you an email. Unfortunately, I wasn't able to find any contact info on your GH profile. Could you please ping me on the donat@gradle.com email address?

**Comment by Lorenzo0111** [comment]
Hi, I wrote you an email.
